Controllers/Admin/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCExamProject.Repository;
using MVCExamProject.Repository.Interfaces;

namespace MVCExamProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
	{

		private readonly IContactUsRepository contactSerive;
		private readonly IStudentRepository studentService;
        private readonly IExamRepository examService;

        public DashboardController(
			IContactUsRepository _contactService,
			IStudentRepository _studentService,
			IExamRepository _examRepository
		)
		{
			contactSerive = _contactService;
            studentService = _studentService;
            examService = _examRepository;
		}

		[Route("admin/dashboard")]
		public IActionResult Index()
		{
			ViewData["studentsCount"] = studentService.count();
            ViewData["messagesCount"] = contactSerive.count();
            ViewData["examsCount"] = examService.count();
            return View("~/Views/Admin/Dashboard.cshtml");
        }
	}
}

Controllers/Admin/ExamController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCExamProject.Models;
using MVCExamProject.Repository.Interfaces;
using MVCExamProject.ViewModel;
using System.Linq;
using MVCExamProject.Enums;
using MVCExamProject.Repository;

namespace MVCExamProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class ExamController : Controller
    {
        private readonly IExamRepository ExamRepo;
        private readonly IExamQuestionRepository QuestionRepo;
        private readonly IQuestionOptionRepository OptionRepo;

        public ExamController(
            IExamRepository _examRepo,
            IExamQuestionRepository questionRepo,
            IQuestionOptionRepository optionRepo
        )
        {
            this.ExamRepo = _examRepo;
            QuestionRepo = questionRepo;
            OptionRepo = optionRepo;

        }

        [Route("admin/exams")]
        public IActionResult Index()
        {
            var exams = ExamRepo.GetAll();
            string responseData = TempData["ResponseData"] as string;
            if (!string.IsNullOrEmpty(responseData))
            {
                ViewData["Response"] = responseData;
            }
            return View("~/Views/Admin/Exam/index.cshtml" , exams);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("admin/exams/create")]
        public IActionResult Create(ExamViewModel data)
        {
            if (ModelState.IsValid)
            {
                // save exam
                Exam exam = new Exam() { Name = data.Title, QuestionCount = int.Parse(data.QuetionsCount) };
                ExamRepo.Insert(exam);

                int questionsCount = int.Parse(data.QuetionsCount);
                for (int i = 1; i <= questionsCount; i++)
                {
                    string questionTitle = Request.Form["Titles" + i];
                    ExamQuestion question = new ExamQuestion()
                    {
                        Title = questionTitle,
                        ExamId = exam.Id
                    };
                    QuestionRepo.Insert(question);

                    int answerNumber = int.Parse(Request.Form["Checks" + i]);
                    for (int s = 1; s <= 4; s++)
                    {
                        string optionTitle = Request.Form["Options" + i + s];
                        QuestionOption option = new QuestionOption()
                        {
                            Title = optionTitle,
                            IsRight = (answerNumber == s) ? true : false,
                            ExamQuestionId = question.Id
                        };
                        OptionRepo.Insert(option);
                    }
                }

                OptionRepo.SaveChanges(); // Save changes to the database
                TempData["ResponseData"] = Responses.success.ToString();
            }
            else
            {
                TempData["ResponseData"] = Responses.fail.ToString();
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        [Route("admin/exams/create")]
        public IActionResult Create()
        {

            return View("~/Views/Admin/Exam/create.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(ExamViewModel data, int id)
        {
            try
            {
                Exam exam = ExamRepo.GetById(id);
                ExamRepo.Delete(exam);
                TempData["ResponseData"] = Responses.success.ToString();
               
            }
            catch(Exception e)
            {
                TempData["ResponseData"] = Responses.fail.ToString();
            }
            return RedirectToAction("Index");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("admin/exams/{id}/edit")]
        public IActionResult Edit(Exam exam)
        {
            var request = Request.Form;
            ExamRepo.Update(exam , request);
            TempData["ResponseData"] = Responses.success.ToString();
            return RedirectToAction("Index");
        }


        [HttpGet]
        [Route("admin/exams/{id}/edit")]
        public IActionResult Edit(int id)
        {
            if (id != null)
            {
                Exam exam = ExamRepo.getExam(id);

                return View("~/Views/Admin/Exam/edit.cshtml" , exam);
            }
            return RedirectToActionPermanent("Index");
        }

    }
}

Controllers/Admin/MessageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCExamProject.Models;
using MVCExamProject.Repository.Interfaces;
using System.Data;

namespace MVCExamProject.Controllers.Admin
{
	[Authorize(Roles = "Admin")]

	public class MessageController : Controller
	{
		private IContactUsRepository contactUsRepository;

		public MessageController(IContactUsRepository contactUsRepo)
		{
			contactUsRepository
				 = contactUsRepo;
		}


		[Route("admin/messages")]
		public IActionResult Index()
		{
			List<ContactUs> contactUsModel = contactUsRepository.GetAll();
			return View("~/Views/Admin/Message/index.cshtml", contactUsModel);
		}



		[Route("admin/messages/delete")]
		public IActionResult Delete(int id)
		{
			ContactUs SelectedRow = contactUsRepository.GetById(id);

			if (SelectedRow != null)
			{
				contactUsRepository.Delete(SelectedRow);
				return RedirectToAction("Index");
			}
			return View("~/Views/Admin/Message/index.cshtml");
		}





	}
}

Controllers/Admin/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using MVCExamProject.Models;
using MVCExamProject.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Data;


namespace MVCExamProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class StudentController : Controller
    {
        private readonly IUserRepository _userRepository;

        public StudentController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }



        //[Authorize("Admin")]
        [Route("admin/students")]
        public IActionResult Index()
        {
            List<User> students = _userRepository.GetAll().Where( u =>u.IsAdmin==false).ToList();
            return View("~/Views/Admin/Student/index.cshtml", students);
        }

        //getbyid
        public IActionResult viewDetails(int id)
        {
            User student = _userRepository.GetById(id);
            return View(student);
        }

        //[Authorize("Admin")]
        [Route("admin/students/delete")]
        public IActionResult Delete(int id)
        {
            User student = _userRepository.GetById(id);

            if (student != null)
            {

                _userRepository.Delete(student);
                return RedirectToAction("Index");

            }
            return View("~/Views/Admin/Student/index.cshtml");
        }

        //search
        public IActionResult searchName(string name) { 
            var result = _userRepository.searchByName(name).Where(u => u.IsAdmin == false).ToList();
            return View("~/Views/Admin/Student/index.cshtml", result);
        }



    }
}

Views/Admin/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Admin/Shared/_AdminLayout.cshtml";
    ViewData["activeLink"] = "dashboard";
}



    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Post-->
        <div class="post d-flex flex-column-fluid" id="kt_post">
            <!--begin::Container-->
            <div id="kt_content_container" class="container-xxl">
                <!--begin::Row-->
                <div class="row g-5 g-xl-8">
                    <div class="col-xl-4">
                        <!--begin::Statistics Widget 5-->
                        <a asp-controller="Exam" asp-action="Index" class="card bg-body-white hoverable card-xl-stretch mb-xl-8">
                            <!--begin::Body-->
                            <div class="card-body">
                                <!--begin::Svg Icon | path: icons/duotune/ecommerce/ecm002.svg-->
                                <span class="svg-icon svg-icon-muted svg-icon-3x">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <path opacity="0.3" d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" fill="black"></path>
                                        <path d="M19 10.4C19 10.3 19 10.2 19 10C19 8.9 18.1 8 17 8H16.9C15.6 6.2 14.6 4.29995 13.9 2.19995C13.3 2.09995 12.6 2 12 2C11.9 2 11.8 2 11.7 2C12.4 4.6 13.5 7.10005 15.1 9.30005C15 9.50005 15 9.7 15 10C15 11.1 15.9 12 17 12C17.1 12 17.3 12 17.4 11.9C18.6 13 19.9 14 21.4 14.8C21.4 14.8 21.5 14.8 21.5 14.9C21.7 14.2 21.8 13.5 21.9 12.7C20.9 12.1 19.9 11.3 19 10.4Z" fill="black"></path>
                                        <path d="M12 15C11 13.1 10.2 11.2 9.60001 9.19995C9.90001 8.89995 10 8.4 10 8C10 7.1 9.40001 6.39998 8.70001 6.09998C8.40001 4.99998 8.20001 3.90005 8.00001 2.80005C7.30001 3.10005 6.70001 3.40002 6.20001 3.90002C6.40001 4.80002 6.50001 5.6 6.80001 6.5C6.40001 6.9 6.10001 7.4 6.10001 8C6.10001 9 6.80001 9.8 7.80001 10C8.30001 11.6 9.00001 13.2 9.70001 14.7C7.10001 13.2 4.70001 11.5 2.40001 9.5C2.20001 10.3 2.10001 11.1 2.10001 11.9C4.60001 13.9 7.30001 15.7 10.1 17.2C10.2 18.2 11 19 12 19C12.6 20 13.2 20.9 13.9 21.8C14.6 21.7 15.3 21.5 15.9 21.2C15.4 20.5 14.9 19.8 14.4 19.1C15.5 19.5 16.5 19.9 17.6 20.2C18.3 19.8 18.9 19.2 19.4 18.6C17.6 18.1 15.7 17.5 14 16.7C13.9 15.8 13.1 15 12 15Z" fill="black"></path>
                                    </svg>
                                </span>
                                <!--end::Svg Icon-->
                                <div class="text-gray-900 fw-bolder fs-2 mb-2 mt-5">
                                    @ViewBag.examsCount
                                </div>
                                <div class="fw-bold text-gray-400">Go to exams</div>
                            </div>
                            <!--end::Body-->
                        </a>
                        <!--end::Statistics Widget 5-->
                    </div>
                    <div class="col-xl-4">
                        <!--begin::Statistics Widget 5-->
                        <a asp-controller="Student" asp-action="Index" class="card bg-primary hoverable card-xl-stretch mb-xl-8">
                            <!--begin::Body-->
                            <div class="card-body">
                                <!--begin::Svg Icon | path: icons/duotune/general/gen008.svg-->
                                <span class="svg-icon svg-icon-white svg-icon-3x ms-n1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <path d="M3 2H10C10.6 2 11 2.4 11 3V10C11 10.6 10.6 11 10 11H3C2.4 11 2 10.6 2 10V3C2 2.4 2.4 2 3 2Z" fill="black"></path>
                                        <path opacity="0.3" d="M14 2H21C21.6 2 22 2.4 22 3V10C22 10.6 21.6 11 21 11H14C13.4 11 13 10.6 13 10V3C13 2.4 13.4 2 14 2Z" fill="black"></path>
                                        <path opacity="0.3" d="M3 13H10C10.6 13 11 13.4 11 14V21C11 21.6 10.6 22 10 22H3C2.4 22 2 21.6 2 21V14C2 13.4 2.4 13 3 13Z" fill="black"></path>
                                        <path opacity="0.3" d="M14 13H21C21.6 13 22 13.4 22 14V21C22 21.6 21.6 22 21 22H14C13.4 22 13 21.6 13 21V14C13 13.4 13.4 13 14 13Z" fill="black"></path>
                                    </svg>
                                </span>
                                <!--end::Svg Icon-->
                                <div class="text-white fw-bolder fs-2 mb-2 mt-5">
                                    @ViewBag.studentsCount
                                </div>
                                <div class="fw-bold text-white">Total Students</div>
                            </div>
                            <!--end::Body-->
                        </a>
                        <!--end::Statistics Widget 5-->
                    </div>
                    <div class="col-xl-4">
                        <!--begin::Statistics Widget 5-->
                        <a asp-controller="Message" asp-action="Index" class="card bg-dark hoverable card-xl-stretch mb-5 mb-xl-8">
                            <!--begin::Body-->
                            <div class="card-body">
                                <!--begin::Svg Icon | path: icons/duotune/arrows/arr070.svg-->
                                <span class="svg-icon svg-icon-muted svg-icon-3x">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <path opacity="0.3" d="M8 8C8 7.4 8.4 7 9 7H16V3C16 2.4 15.6 2 15 2H3C2.4 2 2 2.4 2 3V13C2 13.6 2.4 14 3 14H5V16.1C5 16.8 5.79999 17.1 6.29999 16.6L8 14.9V8Z" fill="black"></path>
                                        <path d="M22 8V18C22 18.6 21.6 19 21 19H19V21.1C19 21.8 18.2 22.1 17.7 21.6L15 18.9H9C8.4 18.9 8 18.5 8 17.9V7.90002C8 7.30002 8.4 6.90002 9 6.90002H21C21.6 7.00002 22 7.4 22 8ZM19 11C19 10.4 18.6 10 18 10H12C11.4 10 11 10.4 11 11C11 11.6 11.4 12 12 12H18C18.6 12 19 11.6 19 11ZM17 15C17 14.4 16.6 14 16 14H12C11.4 14 11 14.4 11 15C11 15.6 11.4 16 12 16H16C16.6 16 17 15.6 17 15Z" fill="black"></path>
                                    </svg>
                                </span>
                                <!--end::Svg Icon-->
                                <div class="text-gray-100 fw-bolder fs-2 mb-2 mt-5">
                                    @ViewBag.messagesCount
                                </div>
                                <div class="fw-bold text-gray-100">Received Messages</div>
                            </div>
                            <!--end::Body-->
                        </a>
                        <!--end::Statistics Widget 5-->
                    </div>
                </div>


            </div>
            <!--end::Container-->
        </div>
        <!--end::Post-->
    </div>

<!--end::Content-->