Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using MVCExamProject.Models;
using MVCExamProject.Repository.Interfaces;

namespace MVCExamProject.Controllers
{
	public class ContactUsController : Controller
	{
		private IContactUsRepository contactUsRepository;

		public ContactUsController(IContactUsRepository contactUsRepo)
		{
			contactUsRepository
				 = contactUsRepo;
		}

		public IActionResult Index()

		{
			return View("~/Views/ContactUs/ContactUs.cshtml");
		}

		//////////////////// Saving Submit
		[HttpPost]
		public IActionResult Index(ContactUs contact)
		{
			if (ModelState.IsValid == true)
			{
				contactUsRepository.Insert(contact);
				TempData["SuccessMessage"] = "Message Sent successfully.";
			}
			TempData["ErrorMessage"] = "Failed To Send Message.";
			return View("~/Views/ContactUs/ContactUs.cshtml", contact);
		}

	}

}

Controllers/StudController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCExamProject.Models;
using MVCExamProject.Repository;
using MVCExamProject.Repository.Interfaces;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace MVCExamProject.Controllers
{
	public class StudController : Controller
	{
		private readonly IExamRepository examService;
        private readonly IExamQuestionRepository examQuestionService;
        private readonly IQuestionOptionRepository questionOptionService;
        private readonly IUserExamRepository userExamService;

        public StudController(IExamRepository examService,IExamQuestionRepository examQuestionService,IQuestionOptionRepository questionOptionService,IUserExamRepository userExamService)
        {
			this.examService = examService;
            this.examQuestionService = examQuestionService;
            this.questionOptionService = questionOptionService;
            this.userExamService = userExamService;
        }

	

		public IActionResult ChooseExam()
		{
			var exams = examService.GetAll();
			return View(exams);
		}
		public IActionResult ExamQuestions(int Id)
		{
            var questionsAndOptions = examService.getExam(Id).ExamQuestions.ToList();
            ViewBag.examId = Id;
            return View(questionsAndOptions);
        }
        [HttpPost]
        public IActionResult Result(List<int> optionsId,int examId)
        {
            
           
            int count = 0;
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            UserExam userExam = new UserExam();
            userExam.ExamId = examId;
            userExam.UserId = int.Parse(userId);
            foreach (int id in optionsId)
            {
                var option = questionOptionService.GetById(id);
                if (option != null && option.IsRight == true)
                {
                    count++;
                }      
            }

            if (count >= 5)
            {
                userExam.IsPassed = true;

            } else { userExam.IsPassed = false; }

            userExam.Degree = count;
            userExam.CreatedAt = DateTime.Now;
            userExamService.Insert(userExam);

            return View(userExam);
        }

    }
}

Controllers/UsersSignInController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MVCExamProject.Attributes;
using MVCExamProject.Data;
using MVCExamProject.Models;
using MVCExamProject.Repository.Interfaces;
using MVCExamProject.ViewModel;
using System.Security.Claims;

namespace MVCExamProject.Controllers
{
    public class UsersSignInController : Controller
    {
        ExamContext context;
        IUserRepository userRepository;
        public UsersSignInController(ExamContext _context, IUserRepository _userRepository)
        {
            context = _context;
            userRepository = _userRepository;

        }

        [HandelError]
        public IActionResult Sign_Up()
        {
            return View();
        }
        [HandelError]
        [HttpPost]
        public IActionResult Sign_Up(SignUPUserViewModel userVM)
        {
            User userdata = new User();

            userdata.Name = userVM.Name;
            userdata.Email = userVM.Email;
            userdata.Password = userVM.Password;
            userdata.Age = userVM.Age;
           
            if (ModelState.IsValid)
            {
                userRepository.Insert(userdata);
                userRepository.Save();

                // create cookie
                ClaimsIdentity claims =
                    new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                claims.AddClaim(new Claim(ClaimTypes.NameIdentifier, userdata.Id.ToString()));
                claims.AddClaim(new Claim(ClaimTypes.Email, userdata.Email));
                claims.AddClaim(new Claim(ClaimTypes.Name, userdata.Name));
                claims.AddClaim(new Claim(ClaimTypes.Role, userRepository.GetRole(userdata.Id)));

                ClaimsPrincipal principal = new ClaimsPrincipal(claims);
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                return RedirectToAction("index", "Home");        //view if user is autho


            }
            return View(userdata);
        }
        public IActionResult Sign_In()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Sign_In(User user)
        {
            if (userRepository.Find(user.Email, user.Password))
            {
               

                User UserAccount = userRepository.GetUserByEmailAndPassword(user.Email, user.Password);

                if (UserAccount.IsAdmin == true)
                {
                    return RedirectToAction("login", "Admin");
                }
                //create cookie
                ClaimsIdentity claims =
                    new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                claims.AddClaim(new Claim(ClaimTypes.NameIdentifier, UserAccount.Id.ToString()));
                claims.AddClaim(new Claim(ClaimTypes.Email, UserAccount.Email));
                claims.AddClaim(new Claim(ClaimTypes.Name, UserAccount.Name));
                claims.AddClaim(new Claim(ClaimTypes.Role, userRepository.GetRole(user.Id)));

                ClaimsPrincipal principal = new ClaimsPrincipal(claims);
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                return RedirectToAction("index", "Home");       //view if user is autho

            }
            return View(user);
        }




        public async Task<IActionResult> Logout()
        {

            // Sign out the user
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("index", "Home");      //view when user log out 
        }
    }
}

Views/Shared/SignInError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Review  these points and try again</h1>

<h3>** passwored and confirm passwored not the same</h3>
<h3>** Email is already exists enter different one</h3>

<a asp-controller="UsersSignIn" asp-action="Sign_Up" class="nav-link"> Sign Up Again</a>

Views/Shared/_FooterPartial.cshtml
<div class="sticky-left d-flex align-items-center bg-white p-3 pt-4 px-4 border border-soft shadow-sm rounded">
	<a target="_blank" asp-controller="ContactUs" asp-action="Index">Contact Us❤️</a>
</div>

<div class="sticky-right">
	<a href="#home"
	   class="icon icon-primary icon-md btn btn-icon-only btn-white border border-soft shadow-soft animate-up-3">
		<span class="fas fa-chevron-up"></span>
	</a>
</div>
<div class="container">
	<div class="row justify-content-between">
		<div class="col-md-4">
			<p>
				At our School Exam Website, we are committed to your success. We
				strive to provide you with the tools, resources, and support you
				need to achieve your academic goals and excel in your exams.
			</p>
			<ul class="social-buttons mb-5 mb-lg-0">
				<li>
					<a href="#"
					   aria-label="twitter social link"
					   class="icon icon-md icon-twitter mr-3">
						<span class="fab fa-twitter"></span>
					</a>
				</li>
				<li>
					<a href="#"
					   class="icon icon-md icon-facebook mr-3"
					   aria-label="facebook social link">
						<span class="fab fa-facebook"></span>
					</a>
				</li>
				<li>
					<a href="#"
					   aria-label="github social link"
					   class="icon icon-md icon-github mr-3">
						<span class="fab fa-github"></span>
					</a>
				</li>
				<li>
					<a href="#"
					   class="icon icon-md icon-dribbble"
					   aria-label="dribbble social link">
						<span class="fab fa-dribbble"></span>
					</a>
				</li>
			</ul>
		</div>
		<div class="col-6 col-md-2 mb-5 mb-lg-0">
			<span class="h5">School Exam Website</span>
			<ul class="footer-links mt-2">
				<li>
					<a target="_blank" asp-controller="Home" asp-action="Index">Home</a>
				</li>
				@*<li>
					<a target="_blank" href="./Exam.html">Take Exam</a>
				</li>*@
				<li>
					<a target="_blank" asp-controller="Home" asp-action="About">About Us</a>
				</li>
				<li>
					<a target="_blank" asp-controller="ContactUs" asp-action="Index">Contact Us</a>
				</li>
			</ul>
		</div>
		<div class="col-12 col-md-4 mb-5 mb-lg-0">
			<span class="h5 mb-3 d-block">Subscribe</span>
			<form asp-controller="ContactUs" asp-action="Index">
				<div class="form-row mb-2">
					<div class="col-12">
						<input type="email"
							   class="form-control mb-2"
							   placeholder="example@company.com"
							   name="email"
							   aria-label="Subscribe form"
							   required />
					</div>
					<div class="col-12">
						<button asp-controller="ContactUs" asp-action="Index"
								class="btn btn-dark shadow-soft btn-block"
								data-loading-text="Sending">
							<span>Subscribe</span>
						</button>
					</div>
				</div>
			</form>
			<p class="text-muted font-small m-0">No spam.</p>
		</div>
	</div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
	<title>@ViewData["Title"] - MVCExamProject</title>

	@*
	Default Links

	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/MVCExamProject.styles.css" asp-append-version="true" />
	*@

	<link type="text/css" href="~/lib/Scripts-For-Template/css/swipe.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/css/sweetalert2.css" />

</head>
<body>
	<header class="header-global" id="home">
		<partial name="_NavbarPartial" />
	</header>
	<br />
	<br />
	<br />


	<main>
		@RenderBody()
	</main>


	<br />
	<br />
	<footer class="footer py-5 pt-lg-6">
		<partial name="_FooterPartial" />
	</footer>




	@*Default Scripts

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

	*@


	@*====================================================================================================Scripts For Template*@
	<!-- Core -->
	<script src="~/lib/Scripts-For-Template/vendor/popper.js/dist/umd/popper.min.js"></script>
	<script src="~/lib/Scripts-For-Template/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="~/lib/Scripts-For-Template/vendor/headroom.js/dist/headroom.min.js"></script>

	<!-- Vendor JS -->
	<script src="~/lib/Scripts-For-Template/vendor/onscreen/dist/on-screen.umd.min.js"></script>
	<script src="~/lib/Scripts-For-Template/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

	<script async defer src="https://buttons.github.io/buttons.js"></script>

	<!-- Swipe JS -->
	<script src="~/lib/Scripts-For-Template/assets/js/swipe.js"></script>

	<!-- Sweet alert -->
	<script src="~/js/sweetalert2.js"></script>

	<script src="~/js/site.js" asp-append-version="true"></script>

	@*===================================================================================================================*@
	@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_NavbarPartial.cshtml
<nav id="navbar-main" aria-label="Primary navigation"
	 class="navbar navbar-main navbar-expand-lg navbar-theme-primary headroom navbar-light navbar-theme-secondary">
	<div class="container position-relative">
		<a class="navbar-brand mr-lg-4" asp-controller="Home" asp-action="Index">
			<img class="navbar-brand-dark"
				 src="~/lib/Scripts-For-Template/assets/img/light.svg"
				 alt="Logo light" />
			<img class="navbar-brand-light"
				 src="~/lib/Scripts-For-Template/assets/img/dark.svg"
				 alt="Logo dark" />
		</a>
		<div class="navbar-collapse collapse mr-auto" id="navbar_global">
			<div class="navbar-collapse-header">
				<div class="row">
					<div class="col-6 collapse-brand">
						<a asp-controller="Home" asp-action="Index">
							<img src="~/lib/Scripts-For-Template/assets/img/dark.svg" alt="Logo dark" />
						</a>
					</div>
					<div class="col-6 collapse-close">
						<a href="#navbar_global"
						   class="fas fa-times"
						   data-toggle="collapse"
						   data-target="#navbar_global"
						   aria-controls="navbar_global"
						   aria-expanded="false"
						   title="close"
						   aria-label="Toggle navigation"></a>
					</div>
				</div>
			</div>

			<ul class="navbar-nav navbar-nav-hover align-items-lg-center">
				<li class="nav-item">
					<a asp-controller="Home" asp-action="Index" class="nav-link"> Home </a>
				</li>
				@if (User.IsInRole("user"))
				{
					<li class="nav-item">
						<a asp-area="" asp-controller="Stud" asp-action="ChooseExam" class="nav-link"> Take Exam </a>
					</li>
				}
				<li class="nav-item">
					<a asp-controller="ContactUs" asp-action="Index" class="nav-link"> Contact Us </a>
				</li>
				<li class="nav-item">
					<a asp-controller="Home" asp-action="About" class="nav-link"> About Us </a>
				</li>
			</ul>

			<ul class="navbar-nav navbar-nav-hover align-items-lg-center">


				@if (!User.Identity.IsAuthenticated)
				{
					<li class="nav-item">
						<a asp-controller="UsersSignIn" asp-action="Sign_In" class="nav-link"> Login </a>
					</li>
					<li class="nav-item">
						<a asp-controller="UsersSignIn" asp-action="Sign_Up" class="nav-link"> Sign Up </a>
					</li>
				}
				@if (User.Identity.IsAuthenticated)
				{
					<li class="nav-item">
						<a asp-controller="UsersSignIn" asp-action="Logout" class="nav-link"> Log Out </a>
					</li>
					<li class="bg-success text-white rounded p-2  pointer-events-none user-select-none">
						<span><b>Welcome @User.Identity.Name</b></span>
					</li>	
				}

				

			</ul>
		</div>
	</div>
</nav>